version: '3.1'
services:
  mysql-server:
    container_name: mysql-server
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/nora/Programs/Data/mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    command: mysqld --max_allowed_packet=32505856 --max_connections=500 --sql_mode="" --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
  phpmyadmin-server:
    container_name: phpmyadmin-server
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql-server
    ports:
      - "808:80"
